services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      PGHOST: ${DB_HOST}
      PGPORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      db:
        condition: service_started
